[tool.poetry]
name = "sqlfluff_sample"
version = "0.0.0"
description = "sqlfluff_sample"
authors = ["yamap55"]
license = "Creative Commons CC0 1.0 Universal (CC0 1.0) Public Domain Dedication"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
# lint
sqlfluff = "1.1.0"
